---
ownership_rules:
  global_allowed_users: [octo-ci]
  directory_matching_rules:
    - name: Kraken CLI formula update
      path: kraken-cli.rb
    - name: Ka Chow CLI formula update
      path: ka-chow-cli.rb
