# Adapted from Homebrew/homebrew-core for this tap.
# Formulae and livecheck strategies are excluded from some strict cops;
# tests (e.g. *_test.rb) are fully checked.
# Root-level *.rb, Formula/**/*.rb, and livecheck/**/*.rb are formula paths.
---
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Include:
    - "**/*.rb"
    - "**/*.rbi"
  Exclude:
    - "**/.github/copilot-instructions.md"
    - "**/vendor/**/*"
  SuggestExtensions:
    rubocop-minitest: false

Layout/ArgumentAlignment:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/IndentationWidth:
  Enabled: false
Layout/LineLength:
  Max: 118
  AllowedPatterns:
    - "#: "
    - ' url "'
    - ' mirror "'
    - " plist_options "
    - ' executable: "'
    - ' font "'
    - ' homepage "'
    - ' name "'
    - ' pkg "'
    - ' pkgutil: "'
    - "    sha256 cellar: "
    - "    sha256  "
    - "#{language}"
    - "#{version."
    - ' "/Library/Application Support/'
    - '"/Library/Caches/'
    - '"/Library/PreferencePanes/'
    - ' "~/Library/Application Support/'
    - '"~/Library/Caches/'
    - '"~/Library/Containers'
    - '"~/Application Support'
    - " was verified as official when first introduced to the cask"
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Exclude:
    - "**/*_spec.rb"
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/DuplicateBranch:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Metrics:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/FileName:
  Regex: !ruby/regexp /^[\w\@\-\+\.]+(\.rb)?$/
Naming/HeredocDelimiterNaming:
  ForbiddenDelimiters:
    - END, EOD, EOF
Naming/InclusiveLanguage:
  CheckStrings: true
  FlaggedTerms:
    slave:
      AllowedRegex:
        - gitslave
        - log_slave
        - ssdb_slave
        - var_slave
        - patches/13_fix_scope_for_show_slave_status_data.patch
Naming/MethodName:
  AllowedPatterns:
    - "\\A(fetch_)?HEAD\\?\\Z"
Naming/MethodParameterName:
  inherit_mode:
    merge:
      - AllowedNames
Naming/PredicateMethod:
  AllowBangMethods: true
Naming/VariableNumber:
  Enabled: false
Style/AndOr:
  EnforcedStyle: always
Style/ArgumentsForwarding:
  Enabled: false
Style/AutoResourceCleanup:
  Enabled: true
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/BlockDelimiters:
  BracesRequiredMethods:
    - sig
Style/ClassAndModuleChildren:
  Exclude:
    - "**/*.rbi"
Style/CollectionMethods:
  Enabled: true
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
  Include:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/Documentation:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
    - "**/*.rbi"
Style/EmptyMethod:
  Exclude:
    - "**/*.rbi"
Style/FetchEnvVar:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
    - "**/*.rbi"
    - "**/Brewfile"
Style/GuardClause:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/HashAsLastArrayItem:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/InverseMethods:
  InverseMethods:
    :blank?: :present?
Style/InvertibleUnlessCondition:
  Enabled: true
  InverseMethods:
    :==: :!=
    :zero?:
    :blank?: :present?
Style/ItBlockParameter:
  EnforcedStyle: only_numbered_parameters
Style/MutableConstant:
  EnforcedStyle: strict
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Style/NumericLiterals:
  MinDigits: 11
  Strict: true
Style/OpenStructUse:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/OptionalBooleanParameter:
  AllowedMethods:
    - respond_to?
    - respond_to_missing?
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/ReturnNil:
  Enabled: true
Style/StderrPuts:
  Enabled: false
Style/StringConcatenation:
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/StringMethods:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/TopLevelMethodDefinition:
  Enabled: true
  Exclude:
    - "*.rb"
    - Formula/**/*.rb
    - livecheck/**/*.rb
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_logical_operators
Style/WordArray:
  MinSize: 4
